USE master
GO
DROP DATABASE IF EXISTS CampingJCV_3
CREATE DATABASE CampingJCV_3
GO
USE CampingJCV_3
GO
ALTER DATABASE CampingJCV_3
ADD FILEGROUP [CampingJCV_FILESTREAM]
CONTAINS FILESTREAM
GO
ALTER DATABASE CampingJCV_3
ADD FILE (
NAME= 'MyDataBaseCampingJCV_filestream',
FILENAME = 'C:\CampingJCV_FILESTREAM'
)
TO FILEGROUP CampingJCV_FILESTREAM
GO
--Activo la Base de Datos
USE CampingJCV_3
GO
DROP TABLE IF EXISTS Images_CampingJCV
GO
CREATE TABLE Images_CampingJCV
(
ID UNIQUEIDENTIFIER ROWGUIDCOL NOT NULL UNIQUE,
imageFile VARBINARY (MAX) FILESTREAM
);
GO